POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01 node JS",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

### 

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/4fcd3e3c-5c52-48b8-9062-246c27ea12d4
Content-Type: application/json

{
    "title": "Video 44",
    "description": "Esse NÃO é o primeiro vídeo",
    "duration": 179
}

###

DELETE http://localhost:3333/videos/19bddc0a-2b29-48d8-beb8-094cd5d33286